### ISSUE TITLE
Unable to find type [Stubble.Core.Builders.StubbleBuilder].

### ISSUE THREAD

**Issue by whihathac** [baldator/Poshstache#10]
I just installed Poshstache on Powershell Core, and it doesn't seem to work. It just throws this error.

`Unable to find type [Stubble.Core.Builders.StubbleBuilder].`

**Comment by baldator** [comment]
Hi @whihathac,

Can you share a little bit more about your setup? which os are you running? how did you install the module?

Thank you,
Marco

**Comment by chwarr** [comment]
I'm encountering this same error with PowerShell 7 running on Windows 10. I used `Install-Module` to install Poshstache 0.1.6 from PSGallery.

```powershell
PS C:\Users\chwarr> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\chwarr> import-module Poshstache
PS C:\Users\chwarr> get-module -name Poshstache

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.1.6                 Poshstache                          ConvertTo-PoshstacheTemplate

PS C:\Users\chwarr> ConvertTo-PoshstacheTemplate -InputString "Hi {{name}}!" -ParametersObject (convertto-json @{name='bob'})
Unable to find type [Stubble.Core.Builders.StubbleBuilder].
```

PowerShell 5.1 works fine:

```powershell
PS C:\Users\chwarr> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\Users\chwarr> import-module Poshstache
PS C:\Users\chwarr> get-module poshstache

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.6      poshstache                          ConvertTo-PoshstacheTemplate


PS C:\Users\chwarr> ConvertTo-PoshstacheTemplate -InputString "Hi {{name}}!" -ParametersObject (convertto-json @{name='bob'})
Hi bob!
```

**Comment by whihathac** [comment]
I have the exact same setup as @chwarr.

**Comment by baldator** [comment]
perfect. Thank you for the hint.
I didn't test it yet on PowerShell 7. Let me add it to build pipeline.

**Comment by Mike-E-angelo** [comment]
+1 here, got [nabbed by this yesterday](https://github.community/t5/GitHub-Actions/New-Exception-on-Running-Workflow/m-p/51304/highlight/true#M8142). 😁

But while I am here I would like to express my gratitude for your efforts here!  Very handy and easy to use. 👍

**Comment by baldator** [comment]
Hi,
I've created a v0.1.8 branch fixing the issue. Could you test it and confirm it is now working as expected?
If it's ok I'll publish it to PowerShell gallery.
Thanks,
Marco

**Comment by whihathac** [comment]
Thanks, this version seems to be working with Powershell Core v7!

**Comment by whihathac** [comment]
Sorry, re-opened since it's not published yet.

**Comment by Mike-E-angelo** [comment]
> Thanks, this version seems to be working with Powershell Core v7!

Cool!

FWIW here is my usage here:
https://github.com/DragonSpark/action-changelog-dawg/blob/master/entrypoint.ps1#L21

I do not see a version or anything, so will this "automagically" fix things once this new version is deployed? :)

**Comment by Mike-E-angelo** [comment]
> I do not see a version or anything, so will this "automagically" fix things once this new version is deployed? :)

I can confirm it does exactly this!

https://github.com/ExtendedXmlSerializer/home/actions/runs/62994799

Thank you all!

**Comment by whihathac** [comment]
Oh I was using the latest version 0.1.8 on Powershell v5.x. Haven't tested it with Powershell Core though..
