### ISSUE TITLE
Allow HashTable parameter

### ISSUE THREAD

**Issue by TaffarelJr** [baldator/Poshstache#19]
I have a Mustache template, and a hashtable containing the values to be substituted. However, when I call `ConvertTo-PoshstacheTemplate` I'm required to pass in a JSON structure. This means I have to convert the hashtable to JSON first, call the method, and then immediately Poshstache converts the JSON back to a hashtable for internal use.

It would be lovely if a hashtable could be passed into the method instead of JSON, and that whole back-and-forth could be skipped entirely.

**Comment by baldator** [comment]
good idea @TaffarelJr! I'm going to implement it.

**Comment by baldator** [comment]
the fix has been implemented in the code in v0.1.9 branch. 
Would you like to test it and confirm if it's fixing your problem?

Thank you

**Comment by TaffarelJr** [comment]
Works great. I pass in my hashtable, add the `-HashTable` switch, and it's golden. Thanks!

As far as it "fixing my problem", I was really just trying to suggest an optimization.  I'm not an expert at PowerShell (which is why I didn't dare submit my own PR :), but I was thinking more along the lines of avoiding the `HashTable -> JSON -> HashTable` conversion loop altogether. Something like this:

(ConvertTo-PoshstacheTemplate.ps1, line 47):
```PowerShell
...
if($HashTable){
    $JSonInput = $ParametersObject
}
else {
    if($PSversiontable.psversion.Major -lt 6){
        $JSonInput = ConvertFrom-JsonToHashtable $ParametersObject
    }
    else{
        $JSonInput = ConvertFrom-Json $ParametersObject -asHashtable
    }
}

if($ValidJSON){
    $JSonInput = ConvertTo-ValidJson $JSonInput
}
...
```
If we pass in a hashtable, there's no reason to go to JSON at all really.

A couple additional notes, if they help:
- It might be nice to rename `$JsonInput` to better reveal its purpose - since it really has nothing to do with JSON by that point. Something like `$hashTable` or `$values` might be more clear.
- I noticed the word `input` was misspelled in the `-HashTable` parameter description. (`imput`) :)

Thanks again, great module!!

**Comment by baldator** [comment]
Thank you for your notes! I changed the code in order to follow your advice.
I merged the change to master and published to PowerShell gallery.

Thank you for your help :)
