### ISSUE TITLE
ConvertTo-PoshstacheTemplate is not recognized

### ISSUE THREAD

**Issue by geographika** [baldator/Poshstache#3]
Thanks for a very useful project!

I was getting the following error when trying the sample code:

```
ConvertTo-PoshstacheTemplate : The term 'ConvertTo-PoshstacheTemplate' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
```
I see this is fixed by https://github.com/baldator/Poshstache/commit/8d076f7d1f7c61ae60964644fb510253fa819990 but this fix is not in the [PowerShell Gallery](https://www.powershellgallery.com/packages/Poshstache/0.1.1)
Is it possible to create a new release?
If not then users can apply the fix themselves to the file installed by default to `C:\Program Files\WindowsPowerShell\Modules\Poshstache\0.1.1\Poshstache.psd1`

**Comment by baldator** [comment]
Hi @geographika,

Thank you for the feedback. I've published a new release and changed the build in order to automatically publish a new version after committing to the master branch.

**Comment by geographika** [comment]
@baldator - thanks a million! I've added a few usage examples based on how I was using the module today.
