### ISSUE TITLE
Can't parse JSON when using PowerShell Core on Mac

### ISSUE THREAD

**Issue by drumbeg** [baldator/Poshstache#8]
I'm encountering issues parsing my JSON using the library. I've cloned the repo and am running tests using Pester. For some reason the "Valid JSON input - Should not Throw" fails. I'm running Powershell 6.2 on a Mac running Mojave.

Additionally I have discovered that the assets used by tests are not valid JSON. Namely, keys have to be strings keys/values should use double quotes, not single.

**Comment by drumbeg** [comment]
I've cloned the repo and am running tests using Pester. For some reason the "Valid JSON input - Should not Throw" fails. I'm running Powershell 6.2 on a Mac running Mojave.

**Comment by baldator** [comment]
Thank you for the feedback. 
I think the problem comes from the PS version you are using. I'm going to create a branch, add the .NET Core version of nustache and I'll ask you to test if it fixes the issue. Hope to have time to do it tonight.

**Comment by baldator** [comment]
The feauter/NETCore branch should fix the issue. Could you please check and confirm if it's the case?

**Comment by ghost** [comment]
Sure. I will check. I managed to replace the call to your `ConvertFrom-JsonToHashtable` code to a `ConvertFrom-Json -asHashtable`, which works for me using Core 6.2, but will test your branch as I need things to be more backwards compatible.

**Comment by ghost** [comment]
I've run your unit tests in my environment and they all pass.

**Comment by ghost** [comment]
Have done more thorough testing on my end in my own project and it's looking good! Thank you.

**Comment by ghost** [comment]
As an aside, does this library support arrays? I can't get my JSON array to render - it is an array of objects with keys.

**Comment by baldator** [comment]
mustache syntax support it: 

---
names: [ {name: chris}, {name: mark}, {name: scott} ]
---

$ cat template.mustache
{{#names}}
  Hi {{name}}!
{{/names}}

$ cat data.yml template.mustache | mustache
Hi chris!
Hi mark!
Hi scott!


I've added some extra pester tests and it looks like the library is not implementing it the proper way. I've even tried to test with stubble (a different mustache implementation) but it isn't working either.
Test templates and objects are in the repo if you want to give it a try.

I'll open an issue on stubble.

**Comment by ghost** [comment]
Thanks. Let me know when the additional tests are there and I will pull, Surprised that Stubble is giving the same problem. Did you test using Powershell Windows or Core?

**Comment by baldator** [comment]
I think I found and fixed the issue.
It should now work for both PowerShell Windows and core.
Could you give It a try? If it works for you, I m going to release a new version of the module.
Thanks you!

**Comment by ghost** [comment]
Hi, I've had success with a simple array, but I need full implementation. ie. Nested objects are now causing me a headache. This is my sample code...

template
`{{app.app_name}}`

data
`{"app":{"app_name":"test"}}`

This fails to output the app_name.

**Comment by baldator** [comment]
I added few tests in order to validate your scenario. It should be ok now.

**Comment by ghost** [comment]
Hi,

I've just been testing for around an hour with a multilevel JSON data source containing objects and arrays and it is working well.

Thanks a lot for this!

**Comment by baldator** [comment]
I've released a new version of the module including all changes with discussed in this thread. I close the issue. 
Let me know in case you would like to see additional features implemented in the module.
Thank you for your help troubleshooting!
